export const dummySkills: SkillRecord[] = [
  {
    id: 'skill-1',
    title: 'Automated Data Scraper',
    slug: 'automated-data-scraper',
    description: 'Fetches structured data from web pages and outputs JSON-ready records for downstream processing.',
    category: 'Data Extraction',
    tags: ['web-scraping', 'data', 'automation'],
    installCommand: 'npm install @skild/automated-data-scraper',
    createdAt: '2026-05-08T08:30:00Z',
    authorClerkId: 'clerk_1234',
    authorEmail: 'data.engineer@skild.dev',
  },
  {
    id: 'skill-2',
    title: 'Browser Task Orchestrator',
    slug: 'browser-task-orchestrator',
    description: 'Orchestrates browser-based workflows using headless automation for login, navigation, and form submission.',
    category: 'Automation',
    tags: ['browser', 'headless', 'workflow'],
    installCommand: 'npm install @skild/browser-task-orchestrator',
    createdAt: '2026-05-07T17:15:00Z',
    authorClerkId: 'clerk_5678',
    authorEmail: 'automation.dev@skild.dev',
  },
  {
    id: 'skill-3',
    title: 'Email Draft Composer',
    slug: 'email-draft-composer',
    description: 'Generates polished email drafts from short prompts, including subject suggestions and tone adjustments.',
    category: 'Communication',
    tags: ['email', 'nlp', 'content-generation'],
    installCommand: 'npm install @skild/email-draft-composer',
    createdAt: '2026-05-06T12:00:00Z',
    authorClerkId: 'clerk_9012',
    authorEmail: 'comms@skild.dev',
  },
  {
    id: 'skill-4',
    title: 'Image Prompt Enhancer',
    slug: 'image-prompt-enhancer',
    description: 'Refines creative prompts for image-generation models to improve composition, style, and clarity.',
    category: 'Creative Tools',
    tags: ['images', 'prompt-engineering', 'ai'],
    installCommand: 'npm install @skild/image-prompt-enhancer',
    createdAt: '2026-05-05T09:45:00Z',
    authorClerkId: null,
    authorEmail: null,
  },
  {
    id: 'skill-5',
    title: 'Usage Analytics Reporter',
    slug: 'usage-analytics-reporter',
    description: 'Collects skill execution metrics and generates summary reports for performance monitoring.',
    category: 'Analytics',
    tags: ['metrics', 'reporting', 'monitoring'],
    installCommand: 'npm install @skild/usage-analytics-reporter',
    createdAt: null,
    authorClerkId: 'clerk_3456',
    authorEmail: 'analytics@skild.dev',
  },
];
