# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3Da061W2NblFMKRUTnxqQfwn2SL", email: "eyramdecutt@gmail.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18zRGEwNXVNa2tpeE5SYU5mNlhTRFEwNHJLQ0oifQ", username: "eyramdecutt"})
}